language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

services:
  - elasticsearch

install:
  - pip install tox tox-travis

script:
  - curl 127.0.0.1:9200
  - tox

after_success:
  - pip install codecov
  - codecov
